
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Mar 11 2026 20:18:09 -03 (Mar 11 2026 23:18:09 UTC)

// Verification Directory fv/can_btu_top 

module can_btu_top(clk, rst_n, prescaler, prop_seg, phase_seg1,
     phase_seg2, sjw, can_rx, sync_en, hard_sync, bit_tick,
     sample_tick, tx_tick, sample_point, bit_time_cnt, sync_locked,
     edge_detected, sync_active);
  input clk, rst_n, can_rx, sync_en, hard_sync;
  input [7:0] prescaler;
  input [2:0] prop_seg, phase_seg1, phase_seg2;
  input [1:0] sjw;
  output bit_tick, sample_tick, tx_tick, sample_point, sync_locked,
       edge_detected, sync_active;
  output [7:0] bit_time_cnt;
  wire clk, rst_n, can_rx, sync_en, hard_sync;
  wire [7:0] prescaler;
  wire [2:0] prop_seg, phase_seg1, phase_seg2;
  wire [1:0] sjw;
  wire bit_tick, sample_tick, tx_tick, sample_point, sync_locked,
       edge_detected, sync_active;
  wire [7:0] bit_time_cnt;
  wire [3:0] phase_seg2_adj;
  wire [3:0] phase_seg1_adj;
  wire [1:0] sync_state;
  wire [7:0] presc_counter;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_214, n_215, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_232, n_233, n_234, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_261;
  wire n_262, n_263, n_264, n_265, n_266, n_267, n_268, n_269;
  wire n_270, n_271, n_272, n_273, n_274, n_275, n_276, n_277;
  wire n_278, n_279, n_280, n_281, n_282, n_283, n_284, n_285;
  wire n_286, n_287, n_288, n_289, n_290, n_291, n_292, n_293;
  wire n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_326;
  wire n_327, n_328, n_329, n_330, phase_adjusted, presc_tick,
       prev_bus_value, sync_done;
  assign bit_time_cnt[5] = 1'b0;
  assign bit_time_cnt[6] = 1'b0;
  assign bit_time_cnt[7] = 1'b0;
  DFFRX1 \phase_seg2_adj_reg[3] (.RN (rst_n), .CK (clk), .D (n_300), .Q
       (phase_seg2_adj[3]), .QN (UNCONNECTED));
  DFFSRXL \phase_seg2_adj_reg[2] (.RN (n_22), .SN (n_5), .CK (clk), .D
       (n_299), .Q (phase_seg2_adj[2]), .QN (UNCONNECTED0));
  DFFSRXL \phase_seg1_adj_reg[2] (.RN (n_1), .SN (n_3), .CK (clk), .D
       (n_298), .Q (phase_seg1_adj[2]), .QN (UNCONNECTED1));
  DFFRX1 \phase_seg1_adj_reg[3] (.RN (rst_n), .CK (clk), .D (n_295), .Q
       (phase_seg1_adj[3]), .QN (UNCONNECTED2));
  INVXL g21158(.A (n_296), .Y (n_300));
  OAI21XL g21159__2398(.A0 (n_275), .A1 (n_297), .B0 (n_250), .Y
       (n_299));
  OAI21XL g21157__5107(.A0 (n_294), .A1 (n_297), .B0 (n_245), .Y
       (n_298));
  AOI22XL g21160__6260(.A0 (n_288), .A1 (n_293), .B0
       (phase_seg2_adj[3]), .B1 (n_289), .Y (n_296));
  OAI21XL g21156__4319(.A0 (n_294), .A1 (n_293), .B0 (n_239), .Y
       (n_295));
  DFFSRXL \phase_seg1_adj_reg[1] (.RN (n_11), .SN (n_7), .CK (clk), .D
       (n_291), .Q (phase_seg1_adj[1]), .QN (UNCONNECTED3));
  DFFSRXL \phase_seg2_adj_reg[1] (.RN (n_9), .SN (n_6), .CK (clk), .D
       (n_292), .Q (phase_seg2_adj[1]), .QN (UNCONNECTED4));
  INVXL g21163(.A (n_290), .Y (n_292));
  NAND2XL g21165__8428(.A (n_243), .B (n_286), .Y (n_291));
  OAI21XL g21166__5526(.A0 (n_283), .A1 (n_287), .B0 (n_284), .Y
       (n_297));
  AOI222XL g21164__6783(.A0 (phase_seg2[1]), .A1 (n_251), .B0
       (phase_seg2_adj[1]), .B1 (n_289), .C0 (n_288), .C1 (n_285), .Y
       (n_290));
  AOI21XL g21167__3680(.A0 (n_176), .A1 (n_287), .B0 (n_183), .Y
       (n_293));
  NAND2BXL g21168__1617(.AN (n_294), .B (n_285), .Y (n_286));
  NAND2XL g21169__2802(.A (n_283), .B (n_287), .Y (n_284));
  ADDFX1 g21170__1705(.A (n_173), .B (n_263), .CI (n_264), .CO (n_287),
       .S (n_285));
  DFFRX1 \tq_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_282), .Q
       (bit_time_cnt[3]), .QN (n_96));
  DFFRX1 \tq_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_281), .Q
       (bit_time_cnt[4]), .QN (n_116));
  DFFRX1 \tq_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_279), .Q
       (bit_time_cnt[2]), .QN (n_271));
  INVXL g21172(.A (n_280), .Y (n_282));
  NAND2XL g21178__5122(.A (n_259), .B (n_278), .Y (n_281));
  DFFSRXL \phase_seg2_adj_reg[0] (.RN (n_2), .SN (n_12), .CK (clk), .D
       (n_276), .Q (phase_seg2_adj[0]), .QN (UNCONNECTED5));
  DFFSRXL \phase_seg1_adj_reg[0] (.RN (n_16), .SN (n_4), .CK (clk), .D
       (n_274), .Q (phase_seg1_adj[0]), .QN (UNCONNECTED6));
  AOI32XL g21173__8246(.A0 (bit_time_cnt[2]), .A1 (n_96), .A2 (n_277),
       .B0 (bit_time_cnt[3]), .B1 (n_266), .Y (n_280));
  OAI21XL g21177__7098(.A0 (n_271), .A1 (n_265), .B0 (n_272), .Y
       (n_279));
  DFFRX1 \tq_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_270), .Q
       (bit_time_cnt[1]), .QN (n_185));
  NAND3XL g21182__6131(.A (bit_time_cnt[3]), .B (bit_time_cnt[2]), .C
       (n_277), .Y (n_278));
  OAI21XL g21190__1881(.A0 (n_275), .A1 (n_273), .B0 (n_252), .Y
       (n_276));
  OAI21XL g21191__5115(.A0 (n_294), .A1 (n_273), .B0 (n_246), .Y
       (n_274));
  DFFRX1 \tq_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_269), .Q
       (bit_time_cnt[0]), .QN (n_267));
  NAND2XL g21181__7482(.A (n_271), .B (n_277), .Y (n_272));
  OAI32XL g21179__4733(.A0 (bit_time_cnt[1]), .A1 (n_267), .A2 (n_268),
       .B0 (n_185), .B1 (n_260), .Y (n_270));
  OAI22XL g21183__6161(.A0 (bit_time_cnt[0]), .A1 (n_268), .B0
       (presc_tick), .B1 (n_267), .Y (n_269));
  OAI21XL g21184__9315(.A0 (bit_time_cnt[2]), .A1 (n_248), .B0 (n_265),
       .Y (n_266));
  OAI22XL g21197__9945(.A0 (n_170), .A1 (n_261), .B0 (n_262), .B1
       (n_255), .Y (n_264));
  NOR2XL g21189__2883(.A (n_258), .B (n_268), .Y (n_277));
  MXI2XL g21200__2346(.A (n_184), .B (n_262), .S0 (n_247), .Y (n_263));
  OAI21XL g21199__1666(.A0 (n_253), .A1 (n_261), .B0 (n_254), .Y
       (n_273));
  AOI21XL g21188__7410(.A0 (n_267), .A1 (n_257), .B0 (n_256), .Y
       (n_260));
  NAND2XL g21187__6417(.A (bit_time_cnt[4]), .B (n_249), .Y (n_259));
  AOI21XL g21192__5477(.A0 (n_258), .A1 (n_257), .B0 (n_256), .Y
       (n_265));
  NOR2XL g21208__2398(.A (phase_seg2[0]), .B (n_261), .Y (n_255));
  NAND2XL g21194__5107(.A (presc_tick), .B (n_257), .Y (n_268));
  NAND2XL g21207__6260(.A (n_253), .B (n_261), .Y (n_254));
  AOI22XL g21195__4319(.A0 (phase_seg2[0]), .A1 (n_251), .B0
       (phase_seg2_adj[0]), .B1 (n_289), .Y (n_252));
  AOI22XL g21196__8428(.A0 (phase_seg2[2]), .A1 (n_251), .B0
       (phase_seg2_adj[2]), .B1 (n_289), .Y (n_250));
  NAND2XL g21193__5526(.A (presc_tick), .B (n_248), .Y (n_249));
  AOI21XL g21212__6783(.A0 (sjw[1]), .A1 (n_242), .B0 (n_241), .Y
       (n_247));
  AOI22XL g21202__3680(.A0 (phase_seg1[0]), .A1 (n_244), .B0
       (phase_seg1_adj[0]), .B1 (n_289), .Y (n_246));
  AOI22XL g21203__1617(.A0 (phase_seg1[2]), .A1 (n_244), .B0
       (phase_seg1_adj[2]), .B1 (n_289), .Y (n_245));
  AOI22XL g21204__2802(.A0 (phase_seg1[1]), .A1 (n_244), .B0
       (phase_seg1_adj[1]), .B1 (n_289), .Y (n_243));
  INVXL g21198(.A (n_248), .Y (n_257));
  MXI2XL g21213__1705(.A (n_46), .B (sjw[0]), .S0 (n_242), .Y (n_261));
  DFFRX1 \sync_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_238), .Q
       (sync_state[0]), .QN (n_27));
  NAND3BXL g21201__5122(.AN (hard_sync), .B (n_224), .C (n_237), .Y
       (n_248));
  NOR2XL g21218__8246(.A (n_214), .B (n_242), .Y (n_241));
  OAI21XL g21210__7098(.A0 (n_240), .A1 (n_236), .B0 (n_294), .Y
       (n_251));
  AOI21XL g21217__6131(.A0 (n_262), .A1 (n_240), .B0 (n_289), .Y
       (n_244));
  NAND2XL g21215__1881(.A (phase_seg1_adj[3]), .B (n_289), .Y (n_239));
  NOR2XL g21209__5115(.A (n_330), .B (n_234), .Y (n_238));
  OAI211XL g21232__7482(.A0 (n_192), .A1 (n_191), .B0 (n_193), .C0
       (n_230), .Y (n_242));
  DFFRX1 sample_tick_reg(.RN (rst_n), .CK (clk), .D (n_233), .Q
       (sample_tick), .QN (UNCONNECTED7));
  DFFRX1 sync_done_reg(.RN (rst_n), .CK (clk), .D (n_232), .Q
       (sync_done), .QN (UNCONNECTED8));
  OAI31XL g21206__4733(.A0 (bit_time_cnt[4]), .A1 (n_223), .A2 (n_222),
       .B0 (n_229), .Y (n_237));
  NOR2XL g21223__6161(.A (hard_sync), .B (n_235), .Y (n_236));
  AOI21XL g21222__9315(.A0 (hard_sync), .A1 (n_225), .B0 (n_235), .Y
       (n_289));
  MXI2XL g21214__9945(.A (sync_state[0]), .B (n_27), .S0 (n_221), .Y
       (n_234));
  DFFRX1 sync_active_reg(.RN (rst_n), .CK (clk), .D (n_227), .Q
       (sync_active), .QN (UNCONNECTED9));
  DFFRX1 phase_adjusted_reg(.RN (rst_n), .CK (clk), .D (n_226), .Q
       (phase_adjusted), .QN (n_135));
  NOR3XL g21231__2883(.A (n_74), .B (n_86), .C (n_219), .Y (n_233));
  OAI22XL g21221__2346(.A0 (n_28), .A1 (n_330), .B0 (n_217), .B1
       (sync_state[0]), .Y (n_232));
  AOI211XL g21238__1666(.A0 (n_203), .A1 (n_202), .B0 (n_204), .C0
       (n_215), .Y (n_230));
  OAI21XL g21211__7410(.A0 (n_209), .A1 (n_199), .B0 (n_220), .Y
       (n_229));
  OR2XL g21236__6417(.A (n_228), .B (n_330), .Y (n_235));
  NAND3BXL g21227__5477(.AN (n_330), .B (n_228), .C (n_262), .Y
       (n_294));
  NOR2XL g21230__2398(.A (n_76), .B (n_330), .Y (n_227));
  NOR2XL g21229__5107(.A (n_34), .B (n_330), .Y (n_226));
  NOR2XL g21234__6260(.A (n_225), .B (n_330), .Y (n_240));
  DFFRX1 \sync_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_218), .Q
       (sync_state[1]), .QN (UNCONNECTED10));
  OAI21XL g21219__4319(.A0 (n_223), .A1 (n_222), .B0 (bit_time_cnt[4]),
       .Y (n_224));
  OAI211XL g21235__8428(.A0 (sync_state[0]), .A1 (n_63), .B0 (n_168),
       .C0 (n_329), .Y (n_221));
  OAI31XL g21220__5526(.A0 (n_210), .A1 (n_198), .A2 (n_197), .B0
       (bit_time_cnt[3]), .Y (n_220));
  OAI211XL g21237__6783(.A0 (phase_adjusted), .A1 (n_143), .B0 (n_149),
       .C0 (n_207), .Y (n_219));
  OAI22XL g21233__3680(.A0 (n_225), .A1 (n_328), .B0 (n_217), .B1
       (n_20), .Y (n_218));
  AOI21XL g21250__2802(.A0 (sjw[0]), .A1 (sjw[1]), .B0 (n_214), .Y
       (n_215));
  DFFRX1 bit_tick_reg(.RN (rst_n), .CK (clk), .D (n_328), .Q
       (bit_tick), .QN (UNCONNECTED11));
  DFFRX1 tx_tick_reg(.RN (rst_n), .CK (clk), .D (n_206), .Q (tx_tick),
       .QN (UNCONNECTED12));
  DFFRX1 sample_point_reg(.RN (rst_n), .CK (clk), .D (n_208), .Q
       (sample_point), .QN (UNCONNECTED13));
  AND2XL g21240__1705(.A (n_212), .B (n_211), .Y (n_223));
  NOR2XL g21239__5122(.A (n_212), .B (n_211), .Y (n_222));
  DFFRX1 \presc_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_200), .Q
       (presc_counter[5]), .QN (UNCONNECTED14));
  DFFRX1 \presc_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_201), .Q
       (presc_counter[3]), .QN (UNCONNECTED15));
  INVXL g21245(.A (n_209), .Y (n_210));
  MX2XL g21248__8246(.A (sample_point), .B (n_187), .S0 (presc_tick),
       .Y (n_208));
  AOI21XL g21258__7098(.A0 (n_195), .A1 (n_194), .B0 (n_196), .Y
       (n_214));
  AOI211XL g21253__6131(.A0 (phase_adjusted), .A1 (n_161), .B0 (n_256),
       .C0 (n_126), .Y (n_207));
  NOR2XL g21251__1881(.A (n_267), .B (n_327), .Y (n_206));
  ADDFX1 g21246__7482(.A (n_150), .B (n_157), .CI (n_169), .CO (n_211),
       .S (n_209));
  OAI22XL g21254__4733(.A0 (n_203), .A1 (n_202), .B0 (sjw[0]), .B1
       (sjw[1]), .Y (n_204));
  INVXL g21267(.A (n_190), .Y (n_201));
  INVXL g21274(.A (n_189), .Y (n_200));
  NOR2XL g21247__6161(.A (n_198), .B (n_197), .Y (n_199));
  NOR2XL g21279__9315(.A (n_195), .B (n_194), .Y (n_196));
  NAND2XL g21255__9945(.A (n_192), .B (n_191), .Y (n_193));
  OAI211XL g21271__2883(.A0 (presc_counter[3]), .A1 (n_37), .B0 (n_47),
       .C0 (n_188), .Y (n_190));
  OAI211XL g21276__2346(.A0 (presc_counter[5]), .A1 (n_53), .B0 (n_70),
       .C0 (n_188), .Y (n_189));
  DFFRX1 \presc_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_180), .Q
       (presc_counter[4]), .QN (n_48));
  DFFRX1 \presc_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_179), .Q
       (presc_counter[6]), .QN (n_71));
  DFFRX1 \presc_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_177), .Q
       (presc_counter[1]), .QN (UNCONNECTED16));
  DFFRX1 \presc_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_178), .Q
       (presc_counter[7]), .QN (UNCONNECTED17));
  DFFRX1 \presc_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_182), .Q
       (presc_counter[0]), .QN (UNCONNECTED18));
  DFFRX1 \presc_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_186), .Q
       (presc_counter[2]), .QN (n_0));
  OAI22XL g21284__7410(.A0 (n_135), .A1 (n_172), .B0 (phase_adjusted),
       .B1 (n_262), .Y (n_187));
  NOR2XL g21268__6417(.A (n_36), .B (n_181), .Y (n_186));
  OAI33XL g21288__5477(.A0 (n_66), .A1 (n_185), .A2 (n_184), .B0
       (bit_time_cnt[1]), .B1 (n_61), .B2 (n_262), .Y (n_202));
  NOR2XL g21285__2398(.A (n_183), .B (n_175), .Y (n_283));
  AOI33XL g21287__5107(.A0 (n_97), .A1 (n_267), .A2 (n_184), .B0
       (bit_time_cnt[0]), .B1 (n_117), .B2 (n_262), .Y (n_194));
  AOI21XL g21289__6260(.A0 (phase_seg2[0]), .A1 (n_184), .B0 (n_171),
       .Y (n_253));
  AOI22XL g21257__4319(.A0 (n_271), .A1 (n_174), .B0 (n_258), .B1
       (n_167), .Y (n_197));
  NOR2XL g21270__8428(.A (presc_counter[0]), .B (n_181), .Y (n_182));
  NOR2XL g21272__5526(.A (n_49), .B (n_181), .Y (n_180));
  NOR2XL g21277__6783(.A (n_72), .B (n_181), .Y (n_179));
  NOR2XL g21278__3680(.A (n_77), .B (n_181), .Y (n_178));
  NOR2XL g21269__1617(.A (n_17), .B (n_181), .Y (n_177));
  OAI221XL g21280__2802(.A0 (n_132), .A1 (n_262), .B0
       (bit_time_cnt[2]), .B1 (n_184), .C0 (n_102), .Y (n_191));
  DFFRX1 presc_tick_reg(.RN (rst_n), .CK (clk), .D (n_181), .Q
       (presc_tick), .QN (n_256));
  INVXL g21291(.A (n_175), .Y (n_176));
  NOR2XL g21273__1705(.A (n_271), .B (n_174), .Y (n_198));
  OAI22XL g21290__5122(.A0 (n_10), .A1 (n_184), .B0 (n_8), .B1 (n_262),
       .Y (n_173));
  INVXL g21282(.A (n_181), .Y (n_188));
  AOI22XL g21299__8246(.A0 (n_128), .A1 (n_165), .B0 (bit_time_cnt[4]),
       .B1 (n_105), .Y (n_172));
  INVXL g21294(.A (n_170), .Y (n_171));
  NOR2XL g21293__7098(.A (phase_seg1[2]), .B (n_184), .Y (n_175));
  INVXL g21295(.A (n_288), .Y (n_275));
  NAND2XL g21286__6131(.A (n_163), .B (n_166), .Y (n_181));
  ADDFX1 g21283__1881(.A (n_90), .B (n_122), .CI (n_151), .CO (n_169),
       .S (n_174));
  NAND2XL g21296__5115(.A (phase_seg1[0]), .B (n_262), .Y (n_170));
  NOR2XL g21297__7482(.A (n_21), .B (n_262), .Y (n_183));
  NOR2XL g21298__4733(.A (n_168), .B (n_262), .Y (n_288));
  OAI21XL g21303__6161(.A0 (bit_time_cnt[1]), .A1 (n_120), .B0 (n_164),
       .Y (n_167));
  AOI22XL g21292__9315(.A0 (n_162), .A1 (n_158), .B0
       (presc_counter[6]), .B1 (n_140), .Y (n_166));
  INVXL g21300(.A (n_262), .Y (n_184));
  OAI211XL g21308__9945(.A0 (n_142), .A1 (n_159), .B0 (n_160), .C0
       (n_155), .Y (n_165));
  AND4XL g21302__2883(.A (n_116), .B (n_130), .C (n_133), .D (n_153),
       .Y (n_262));
  OAI22XL g21307__2346(.A0 (n_106), .A1 (n_137), .B0 (n_121), .B1
       (n_152), .Y (n_164));
  AOI22XL g21301__1666(.A0 (n_162), .A1 (n_148), .B0 (n_123), .B1
       (presc_counter[7]), .Y (n_163));
  NAND3XL g21321__7410(.A (n_160), .B (n_159), .C (n_154), .Y (n_161));
  AOI211XL g21305__6417(.A0 (n_113), .A1 (n_100), .B0 (n_147), .C0
       (n_141), .Y (n_158));
  XOR2XL g21311__5477(.A (n_144), .B (n_156), .Y (n_157));
  NOR2XL g21314__2398(.A (n_156), .B (n_146), .Y (n_212));
  NAND2XL g21322__5107(.A (n_68), .B (n_154), .Y (n_155));
  OAI21XL g21306__6260(.A0 (n_98), .A1 (n_134), .B0 (n_56), .Y (n_153));
  NOR3XL g21320__4319(.A (n_59), .B (n_73), .C (n_136), .Y (n_152));
  NAND2XL g21315__8428(.A (n_125), .B (n_150), .Y (n_151));
  AOI22XL g21323__5526(.A0 (phase_adjusted), .A1 (n_129), .B0
       (bit_time_cnt[4]), .B1 (n_145), .Y (n_149));
  OAI31XL g21309__6783(.A0 (n_109), .A1 (n_48), .A2 (n_147), .B0
       (n_111), .Y (n_148));
  OAI22XL g21327__3680(.A0 (phase_seg2_adj[3]), .A1 (n_145), .B0
       (n_144), .B1 (n_115), .Y (n_146));
  INVXL g21326(.A (n_192), .Y (n_143));
  AOI21XL g21338__1617(.A0 (n_271), .A1 (n_124), .B0 (n_142), .Y
       (n_154));
  OAI22XL g21319__2802(.A0 (n_110), .A1 (presc_counter[4]), .B0
       (n_112), .B1 (presc_counter[3]), .Y (n_141));
  NOR2XL g21316__1705(.A (n_139), .B (n_138), .Y (n_140));
  AOI21XL g21310__5122(.A0 (n_139), .A1 (n_71), .B0 (n_138), .Y
       (n_162));
  INVXL g21333(.A (n_136), .Y (n_137));
  OAI22XL g21325__8246(.A0 (n_89), .A1 (phase_adjusted), .B0 (n_135),
       .B1 (n_107), .Y (n_150));
  AOI22XL g21324__7098(.A0 (phase_adjusted), .A1 (n_127), .B0 (n_104),
       .B1 (n_135), .Y (n_156));
  NOR2XL g21313__6131(.A (n_131), .B (n_118), .Y (n_134));
  OR3XL g21317__1881(.A (n_132), .B (n_271), .C (n_131), .Y (n_133));
  NAND2XL g21332__5115(.A (n_130), .B (n_114), .Y (n_192));
  INVXL g21354(.A (n_128), .Y (n_129));
  NOR2XL g21337__7482(.A (n_94), .B (n_119), .Y (n_136));
  NOR2XL g21349__4733(.A (bit_time_cnt[3]), .B (n_127), .Y (n_142));
  NOR2XL g21318__6161(.A (phase_adjusted), .B (n_203), .Y (n_126));
  AOI33XL g21328__9315(.A0 (phase_seg2[2]), .A1 (n_132), .A2 (n_135),
       .B0 (phase_adjusted), .B1 (phase_seg2_adj[2]), .B2 (n_124), .Y
       (n_125));
  NOR2XL g21359__9945(.A (n_123), .B (presc_counter[7]), .Y (n_138));
  NAND2XL g21352__2883(.A (bit_time_cnt[3]), .B (n_127), .Y (n_160));
  NOR2XL g21353__2346(.A (n_121), .B (n_101), .Y (n_122));
  INVXL g21348(.A (n_119), .Y (n_120));
  AOI21XL g21330__1666(.A0 (n_117), .A1 (bit_time_cnt[2]), .B0 (n_95),
       .Y (n_118));
  NAND2XL g21358__7410(.A (n_116), .B (n_115), .Y (n_128));
  NAND2XL g21351__6417(.A (phase_adjusted), .B (n_115), .Y (n_145));
  INVXL g21341(.A (n_131), .Y (n_114));
  AOI22XL g21335__5477(.A0 (n_112), .A1 (presc_counter[3]), .B0 (n_99),
       .B1 (presc_counter[2]), .Y (n_113));
  NAND2XL g21342__2398(.A (n_108), .B (presc_counter[5]), .Y (n_111));
  INVXL g21340(.A (n_109), .Y (n_110));
  NAND2XL g21331__5107(.A (n_103), .B (n_93), .Y (n_139));
  NOR2XL g21336__6260(.A (n_108), .B (presc_counter[5]), .Y (n_147));
  NOR2XL g21364__4319(.A (phase_seg2_adj[2]), .B (n_124), .Y (n_107));
  NOR2XL g21350__8428(.A (n_121), .B (n_106), .Y (n_119));
  OR2XL g21366__5526(.A (n_271), .B (n_124), .Y (n_159));
  OAI21XL g21372__6783(.A0 (phase_seg1_adj[3]), .A1 (n_91), .B0
       (n_105), .Y (n_127));
  NAND2XL g21346__3680(.A (n_104), .B (bit_time_cnt[3]), .Y (n_130));
  NAND2XL g21368__1617(.A (prescaler[7]), .B (n_103), .Y (n_123));
  NAND2XL g21345__2802(.A (n_92), .B (n_88), .Y (n_109));
  NOR2XL g21347__1705(.A (n_104), .B (bit_time_cnt[3]), .Y (n_131));
  OAI21XL g21339__5122(.A0 (n_132), .A1 (bit_time_cnt[2]), .B0 (n_102),
       .Y (n_203));
  INVXL g21361(.A (n_106), .Y (n_101));
  OAI211XL g21367__8246(.A0 (n_99), .A1 (presc_counter[2]), .B0 (n_65),
       .C0 (n_75), .Y (n_100));
  INVXL g21362(.A (n_105), .Y (n_115));
  NOR3XL g21343__7098(.A (n_97), .B (n_132), .C (n_96), .Y (n_98));
  AOI21XL g21334__6131(.A0 (n_132), .A1 (n_271), .B0 (n_94), .Y (n_95));
  OAI21XL g21344__1881(.A0 (prescaler[5]), .A1 (n_92), .B0
       (prescaler[6]), .Y (n_93));
  XOR2XL g21369__5115(.A (n_92), .B (prescaler[5]), .Y (n_108));
  NAND2XL g21357__7482(.A (n_132), .B (bit_time_cnt[2]), .Y (n_102));
  NAND2XL g21377__4733(.A (phase_seg1_adj[3]), .B (n_91), .Y (n_105));
  OAI21XL g21371__6161(.A0 (n_81), .A1 (n_80), .B0 (n_90), .Y (n_106));
  OAI21XL g21375__9315(.A0 (n_84), .A1 (n_82), .B0 (n_83), .Y (n_124));
  NOR2XL g21355__9945(.A (phase_seg2[2]), .B (n_132), .Y (n_89));
  OAI21XL g21356__2883(.A0 (prescaler[3]), .A1 (n_87), .B0
       (prescaler[4]), .Y (n_88));
  XOR2XL g21374__2346(.A (n_87), .B (prescaler[3]), .Y (n_112));
  NAND2BXL g21373__1666(.AN (n_92), .B (n_24), .Y (n_103));
  NOR2XL g21360__7410(.A (n_79), .B (n_85), .Y (n_104));
  MX2XL g21365__6417(.A (n_195), .B (n_69), .S0 (phase_adjusted), .Y
       (n_86));
  ADDFX1 g21363__5477(.A (phase_seg1[2]), .B (n_84), .CI (n_51), .CO
       (n_85), .S (n_132));
  NAND2XL g21378__2398(.A (n_84), .B (n_82), .Y (n_83));
  NAND2XL g21376__5107(.A (n_81), .B (n_80), .Y (n_90));
  NAND3BXL g21387__6260(.AN (n_79), .B (n_41), .C (n_58), .Y (n_91));
  AOI21XL g21392__4319(.A0 (prescaler[2]), .A1 (n_64), .B0 (n_78), .Y
       (n_99));
  NAND2XL g21380__8428(.A (n_25), .B (n_78), .Y (n_92));
  NOR2XL g21304__5526(.A (presc_counter[7]), .B (n_60), .Y (n_77));
  AOI22XL g21396__6783(.A0 (n_225), .A1 (n_62), .B0 (sync_active), .B1
       (n_19), .Y (n_76));
  NAND2XL g21391__3680(.A (prescaler[1]), .B (n_55), .Y (n_75));
  INVXL g21381(.A (n_78), .Y (n_87));
  AOI22XL g21400__1617(.A0 (n_267), .A1 (n_73), .B0 (bit_time_cnt[0]),
       .B1 (n_52), .Y (n_74));
  MXI2XL g21312__2802(.A (n_71), .B (presc_counter[6]), .S0 (n_70), .Y
       (n_72));
  MXI2XL g21383__1705(.A (n_185), .B (bit_time_cnt[1]), .S0 (n_67), .Y
       (n_69));
  OAI21XL g21382__5122(.A0 (n_42), .A1 (n_67), .B0 (n_44), .Y (n_68));
  OAI22XL g21385__8246(.A0 (n_66), .A1 (phase_adjusted), .B0 (n_135),
       .B1 (n_67), .Y (n_80));
  NAND2BXL g21397__7098(.AN (n_64), .B (n_35), .Y (n_65));
  NOR2XL g21402__6131(.A (sync_state[1]), .B (n_62), .Y (n_63));
  XNOR2XL g21384__1881(.A (phase_seg1_adj[2]), .B (n_57), .Y (n_82));
  NOR2XL g21399__5115(.A (prescaler[2]), .B (n_64), .Y (n_78));
  AOI22XL g21389__7482(.A0 (n_61), .A1 (n_185), .B0 (n_66), .B1
       (bit_time_cnt[1]), .Y (n_195));
  NOR2XL g21329__4733(.A (n_71), .B (n_70), .Y (n_60));
  AND2XL g21406__6161(.A (n_59), .B (n_73), .Y (n_121));
  OAI21XL g21390__9315(.A0 (n_84), .A1 (phase_seg1_adj[2]), .B0 (n_57),
       .Y (n_58));
  OAI211XL g21386__9945(.A0 (n_97), .A1 (n_185), .B0 (n_66), .C0
       (n_258), .Y (n_56));
  AOI21XL g21398__2883(.A0 (n_54), .A1 (presc_counter[0]), .B0
       (presc_counter[1]), .Y (n_55));
  NAND2XL g21405__2346(.A (n_217), .B (n_45), .Y (n_62));
  NAND2BXL g21404__1666(.AN (prescaler[1]), .B (n_54), .Y (n_64));
  ADDFX1 g21395__7410(.A (n_50), .B (phase_seg1_adj[1]), .CI (n_30),
       .CO (n_57), .S (n_67));
  NAND2XL g21370__6417(.A (presc_counter[5]), .B (n_53), .Y (n_70));
  INVXL g21393(.A (n_66), .Y (n_61));
  INVXL g21409(.A (n_52), .Y (n_73));
  ADDFX1 g21394__5477(.A (phase_seg1[1]), .B (n_33), .CI (n_50), .CO
       (n_51), .S (n_66));
  MXI2XL g21379__2398(.A (n_48), .B (presc_counter[4]), .S0 (n_47), .Y
       (n_49));
  OAI22XL g21413__5107(.A0 (n_117), .A1 (phase_adjusted), .B0 (n_135),
       .B1 (n_43), .Y (n_52));
  AOI22XL g21416__6260(.A0 (n_97), .A1 (bit_time_cnt[0]), .B0 (n_117),
       .B1 (n_267), .Y (n_46));
  NAND3BXL g21415__4319(.AN (sync_done), .B (sync_en), .C
       (edge_detected), .Y (n_45));
  NOR2XL g21408__8428(.A (prescaler[0]), .B (n_40), .Y (n_54));
  NOR2XL g21388__5526(.A (n_48), .B (n_47), .Y (n_53));
  OAI21XL g21410__6783(.A0 (bit_time_cnt[0]), .A1 (n_43), .B0
       (bit_time_cnt[1]), .Y (n_44));
  DFFRX1 sync_locked_reg(.RN (rst_n), .CK (clk), .D (n_39), .Q
       (sync_locked), .QN (UNCONNECTED19));
  NOR2XL g21418__3680(.A (n_18), .B (n_43), .Y (n_42));
  NAND2XL g21403__1617(.A (n_84), .B (phase_seg1_adj[2]), .Y (n_41));
  NOR4XL g21414__2802(.A (prescaler[7]), .B (prescaler[2]), .C
       (prescaler[1]), .D (n_26), .Y (n_40));
  NAND3BXL g21411__1705(.AN (sync_done), .B (n_267), .C (n_326), .Y
       (n_39));
  NAND2XL g21401__5122(.A (presc_counter[3]), .B (n_37), .Y (n_47));
  AOI21XL g21412__8246(.A0 (presc_counter[2]), .A1 (n_35), .B0 (n_32),
       .Y (n_36));
  DFFRX1 edge_detected_int_reg(.RN (rst_n), .CK (clk), .D (n_31), .Q
       (edge_detected), .QN (UNCONNECTED20));
  INVXL g21422(.A (n_97), .Y (n_117));
  NOR2XL g21427__7098(.A (phase_adjusted), .B (n_228), .Y (n_34));
  OAI21XL g21432__6131(.A0 (n_13), .A1 (phase_seg1_adj[0]), .B0 (n_29),
       .Y (n_43));
  XNOR2X1 g21417__1881(.A (n_23), .B (prop_seg[2]), .Y (n_84));
  AOI21XL g21434__5115(.A0 (prop_seg[0]), .A1 (n_14), .B0 (n_33), .Y
       (n_97));
  NOR2XL g21419__7482(.A (presc_counter[2]), .B (n_35), .Y (n_32));
  AOI22XL g21428__4733(.A0 (phase_seg2[1]), .A1 (n_135), .B0
       (phase_seg2_adj[1]), .B1 (phase_adjusted), .Y (n_81));
  AOI22XL g21429__6161(.A0 (phase_seg2[0]), .A1 (n_135), .B0
       (phase_seg2_adj[0]), .B1 (phase_adjusted), .Y (n_59));
  INVXL g21438(.A (n_228), .Y (n_168));
  NOR2XL g21420__9315(.A (n_0), .B (n_35), .Y (n_37));
  NOR2XL g21431__9945(.A (can_rx), .B (prev_bus_value), .Y (n_31));
  INVXL g21437(.A (n_29), .Y (n_30));
  AOI21XL g21425__2883(.A0 (sync_state[1]), .A1 (n_27), .B0
       (sync_done), .Y (n_28));
  NAND2XL g21430__2346(.A (n_25), .B (n_24), .Y (n_26));
  NOR2BX1 g21421__1666(.AN (prop_seg[2]), .B (n_23), .Y (n_79));
  NAND2XL g21452__7410(.A (n_15), .B (n_21), .Y (n_22));
  INVXL g21435(.A (n_19), .Y (n_20));
  INVXL g21436(.A (n_94), .Y (n_18));
  XNOR2XL g21426__6417(.A (presc_counter[1]), .B (presc_counter[0]), .Y
       (n_17));
  NAND2XL g21442__5477(.A (n_15), .B (n_14), .Y (n_16));
  NAND2XL g21449__2398(.A (n_13), .B (phase_seg1_adj[0]), .Y (n_29));
  XOR2XL g21433__5107(.A (prop_seg[0]), .B (prop_seg[1]), .Y (n_50));
  NOR2XL g21450__4319(.A (sync_state[1]), .B (n_27), .Y (n_228));
  NAND2XL g21457__8428(.A (phase_seg2[0]), .B (n_15), .Y (n_12));
  NAND2XL g21454__5526(.A (n_15), .B (n_10), .Y (n_11));
  NAND2XL g21451__6783(.A (n_15), .B (n_8), .Y (n_9));
  NAND2XL g21459__3680(.A (phase_seg1[1]), .B (n_15), .Y (n_7));
  NAND2XL g21456__1617(.A (phase_seg2[1]), .B (n_15), .Y (n_6));
  NAND2XL g21453__2802(.A (phase_seg2[2]), .B (n_15), .Y (n_5));
  NAND2XL g21455__1705(.A (phase_seg1[0]), .B (n_15), .Y (n_4));
  NAND2XL g21458__5122(.A (phase_seg1[2]), .B (n_15), .Y (n_3));
  NOR2XL g21463__8246(.A (prop_seg[0]), .B (n_14), .Y (n_33));
  NAND2XL g21444__7098(.A (phase_seg2_adj[3]), .B (phase_adjusted), .Y
       (n_144));
  NAND2XL g21443__6131(.A (sync_state[1]), .B (sync_state[0]), .Y
       (n_19));
  NOR2XL g21445__1881(.A (bit_time_cnt[0]), .B (bit_time_cnt[1]), .Y
       (n_94));
  NOR2XL g21448__5115(.A (sync_state[0]), .B (sync_state[1]), .Y
       (n_225));
  NAND2XL g21446__7482(.A (presc_counter[1]), .B (presc_counter[0]), .Y
       (n_35));
  NAND2XL g21447__4733(.A (bit_time_cnt[0]), .B (bit_time_cnt[1]), .Y
       (n_258));
  DFFSX1 prev_bus_value_reg(.SN (rst_n), .CK (clk), .D (can_rx), .Q
       (UNCONNECTED21), .QN (prev_bus_value));
  OR2XL g21440__6161(.A (phase_seg2[0]), .B (rst_n), .Y (n_2));
  OR2XL g21439__9315(.A (phase_seg1[2]), .B (rst_n), .Y (n_1));
  NOR2XL g21461__9945(.A (prescaler[3]), .B (prescaler[4]), .Y (n_25));
  NOR2XL g21460__2883(.A (prescaler[5]), .B (prescaler[6]), .Y (n_24));
  NAND2XL g21462__2346(.A (prop_seg[0]), .B (prop_seg[1]), .Y (n_23));
  INVXL g21475(.A (phase_seg2[2]), .Y (n_21));
  INVXL g21473(.A (phase_seg2[1]), .Y (n_8));
  INVXL g21478(.A (phase_seg1[1]), .Y (n_10));
  INVXL g21476(.A (prop_seg[0]), .Y (n_13));
  INVXL g21474(.A (phase_seg1[0]), .Y (n_14));
  INVXL g21477(.A (hard_sync), .Y (n_217));
  INVXL g21480(.A (rst_n), .Y (n_15));
  NOR2XL g49(.A (hard_sync), .B (n_329), .Y (n_330));
  INVXL g50(.A (n_328), .Y (n_329));
  NOR2XL g51(.A (bit_time_cnt[0]), .B (n_327), .Y (n_328));
  NAND2XL g52(.A (presc_tick), .B (n_326), .Y (n_327));
  NOR4XL g53(.A (bit_time_cnt[4]), .B (bit_time_cnt[1]), .C
       (bit_time_cnt[3]), .D (bit_time_cnt[2]), .Y (n_326));
endmodule

